name: Test Workflow CI
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
 

permissions:
  contents: read
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'
      
      - name: Prepare to test
        run: |
          java -version
          chmod +x gradlew
          ./gradlew -v

      - name: Test with Gradle
        run: |
          ./gradlew clean test --continue
        continue-on-error: true
      
      # - name: Create test results directory
      #   run: |
      #     rm -rf test-results
      #     mkdir test-results
      #     for proj in pj-*; do \
      #       test_results_dir="$proj/build/test-results/test"; \
      #       [ -d "$test_results_dir" ] && mv  "$test_results_dir"/*.xml  "test-results/"; \
      #     done

          
      # - name: Upload failure reports when test fails
      #   if: failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: junit-test-failure-report
      #     path: |
      #       ${{ github.workspace }}/**/build/reports/tests
            
      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          # path: test-results
          path: |
            ${{ github.workspace }}/**/build/test-results/test
            ${{ github.workspace }}/**/build/reports/tests/test
            ${{ github.workspace }}/**/build/test-results/TEST-*.xml
          retention-days: 3
  
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
            paths: |
              ${{ github.workspace }}/**/build/reports/jacoco/**/*.xml
            token: ${{ secrets.GITHUB_TOKEN }}
            min-coverage-overall: 40
            min-coverage-changed-files: 60

      - name: Upload JUnit test jacoco report
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          # path: test-results
          path: |
           ${{ github.workspace }}/**/build/reports/jacoco/
          retention-days: 1

  report:
    name: Generate Report
    needs: test
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JUnit test results
        uses: actions/download-artifact@v4
        with:
          name: junit-test-results

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JUnit Testing
          path: '**/TEST-*.xml'
          reporter: java-junit
          max-annotations: 50
          list-tests: failed
          path-replace-backslashes: false
          list-suites: all
          fail-on-error: true
          only-summary: true