name: Test Workflow CI
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
 

permissions:
  contents: read
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'
      
      - name: Prepare to test
        run: |
          java -version
          chmod +x gradlew
          ./gradlew -v

      - name: Test with Gradle
        run: |
          ./gradlew clean test --continue
          rm -rf test-results
          mkdir test-results
          for proj in pj-*; do \
            test_results_dir="$proj/build/test-results/test"; \
            [ -d "$test_results_dir" ] && mv  "$test_results_dir"/*.xml  "test-results/"; \
          done
        continue-on-error: true

      - name: Upload failure reports when test fails
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-failure-report
          path: |
            ${{ github.workspace }}/**/build/reports/tests
            
      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: test-results
          retention-days: 3

  report:
    name: Generate Report
    needs: test
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JUnit test results
        uses: actions/download-artifact@v4
        with:
          name: junit-test-results

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JUnit Testing
          path: '**/TEST-*.xml'
          reporter: java-junit
